### ISSUE TITLE
adding licence file

### ISSUE THREAD

**Issue by netpipe** [multishell/sash#1]
please add licence :+1:

**Comment by fidian** [comment]
Normally I add a `LICENSE.md` file to each repository I create. In this case, I am unable to legally do this.

The code is not mine. This is just a git repository that contains each released version of the shell. Here's information I have from another repository.

https://github.com/multishell/multishell-scripts/blob/master/sash/README.md

Sash
====

Stand-alone shell, which has several utilities built into it. Ideal for rescuing a system as it is statically compiled.

Source: http://members.canb.auug.org.au/~dbell/programs/

The "plus patches" version (marked as `*-fmb`) adds `chroot`, `pivot_root`, and `losetup` to versions 3.5 through 3.7. I've also backported it to 3.4. As of version 3.8, those patches are included by the original maintainer.

Sash plus patches: http://www.baiti.net/sash/
